#!/bin/sh

set -e

dir=$1 ; shift

git clone -b master --single-branch --depth 1 "git@github.com:${DEPLOY_REPO_SLUG}.git" "$dir"

# Embed a commit date and hash.  like a "2016-04-16T11:57:44+09:00 48ae020"
commit_info="$(git log -1 generator --format='%cI %h')"
repl_keyword="___GENERATOR_COMMIT_DATE_AND_HASH___"
sed -i -e "s/$repl_keyword/$commit_info/" vim.vim

# install
cp -f vim.vim "$dir/syntax/"

cd "$dir"
git add --all
if ! git diff --quiet HEAD ; then
  git config push.default simple
  git config user.email "$DEPLOY_USER_EMAIL"
  git config user.name "$DEPLOY_USER_NAME"
  git commit -m "Generated by Travis JOB $TRAVIS_JOB_NUMBER

https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
  git push
else
  echo "No changes"
fi
